### ISSUE TITLE
Where is the rmp2018_schema.sql file?

### ISSUE THREAD

**Issue by gordonje** [rji-futures-lab/django-rmp-data#10]
The `rmp2018.zip` file provided by Matt included a `readme.txt` file that mentioned a `rmp2018_schema.sql` file that can be used to generate the `CREATE TABLE` statements for all the database tables.

If we can get that file, maybe we can skip the process outlined in #1.

It's also possible the SQL in this schema file would included syntax that is incompatible with postgres, our chosen RDBMS for this project (because we'll be using django-postgres-copy).

Still...could have some valuable clues for defining our schema.

**Comment by mizzousundevil** [comment]
Yeah if I don't have these files for this and the record layout in my email/files, I'll bug Rich, who should. He's the guy who created the original RTK coding etc.

**Comment by mizzousundevil** [comment]
I've asked Rich for it. I don't see the files in any of my other possible locations. I'll pester him again before I leave  and again at the start of the day tomorrow

**Comment by gordonje** [comment]
Thanks, @mizzousundevil. Not a show stopper if we can't find them.

**Comment by mizzousundevil** [comment]
Rich says he'll provide this but we haven't seen it yet.
