### ISSUE TITLE
Data Tables not rendering properly

### ISSUE THREAD

**Issue by thomasoide** [rji-futures-lab/django-rmp-data#102]
The JS plugin we used to render our pages with tables, allowing for pagination and sorting, isn't rendering in production for whatever reason. It does work in the current development environment.

**Comment by gordonje** [comment]
The feature that should be there (but isn't) is the clickable headers for sorting, right? The server logs show a 404 for `/static/rmp/script.js`. But I don't see this file in our repo or in the history. Is it missing?

**Comment by thomasoide** [comment]
I got it, failed to notice that the static directory on my branch is in the .gitignore file, which means the script I created never got merged to master. Will email you the script file now so that you can run collect static
