### ISSUE TITLE
Where is the RMP data dictionary?

### ISSUE THREAD

**Issue by gordonje** [rji-futures-lab/django-rmp-data#11]
The `rmp2018.zip` file provided by Matt included a `readme.txt` file with the following comment:

> Additional information about the database can be found in RTK NET's "About the Data" and "Data Dictionary" pages.

Sounds like reference to [this page](http://www.rtk.net/rmp/datadictionary.php) (which is found under [this](http://www.rtk.net/rmp/genhelp.php) higher level description of the RMP data).

I would have thought that what I'm seeing on the RMP data dictionary page would reflect what I see in the [`db_fields.tsv`](https://github.com/rji-futures-lab/django-rmp-data/blob/master/resources/db_fields.tsv) file (also in the same .zip file). These seem like different record layouts, though. Requires further digging.

Either way, a machine-readable data dictionary file (or set of files) would be useful if we can get it.

**Comment by mizzousundevil** [comment]
Sorry for the delay on this. I'm digging around and looking for this right now.

**Comment by mizzousundevil** [comment]
Rich said he'll get us a better data dictionary but I haven't seen it yet.

**Comment by mizzousundevil** [comment]
Bugging Rich again for this
