### ISSUE TITLE
Some questions about tables

### ISSUE THREAD

**Issue by thomasoide** [rji-futures-lab/django-rmp-data#13]
I figured out how to crack open the raw .mdb files and am now trying to figure out how to get from the raw data to the processed data. 

Matt, I have a few questions about a some of the tables. I was hoping you could take a look at tables I still have questions about and give me a bit of insight. 

rmp_lepc_cd - This file is just empty.

rmp_proc_chem, rmp_proc_naics, rmp_registration - I'm specifically confused about the columns that begin with "num_ " I'm assuming the values in those columns are boolean, but since I'm not super-familiar, I could be wrong. Do you have a better idea for what those columns mean? 

I'll probably have some questions later down the line, but these are the initial questions about the data I have so far.

**Comment by mizzousundevil** [comment]
I'll take a look at this today.  My guess is you're right, but I have to take a look at it to be 100%

**Comment by mizzousundevil** [comment]
Oh and my guess on the lepc_cd thing is it was probably related to a mapping initiative they scrapped when moved the data to us.  Like it was going to be Local Emergency Planning Committees (LEPCs) paired to Congressional Districts? Just a guess
