### ISSUE TITLE
Nulls in Boolean fields

### ISSUE THREAD

**Issue by gordonje** [rji-futures-lab/django-rmp-data#23]
As I'm working through the data models, I am noticing Boolean columns that contain NULL values in the raw source csv files. For example, `OffsiteDeaths` column in `tblS6AccidentHistory.csv` has six lines where this column value is an empty string:

```sh
csvstat -c OffsiteDeaths --freq data/rmp/raw/tblS6AccidentHistory.csv
```

But if you look in the corresponding column in the processed .tsv files—`offsite_deaths` in `rmp_accident.tsv`—these NULLs are converted to False:

```sh
csvstat -c offsite_deaths -t --freq data/rmp/processed/rmp_accident.tsv
```

This could be bad. Unless we've confident understanding that NULL in these fields is the equivalent of False, then we could be shading the truth here. It might be the case that NULL value in these fields means "unobserved" or  "not recorded".

Seems like a question for the record custodians.

**Comment by thomasoide** [comment]
<img width="1380" alt="screen shot 2018-10-23 at 6 12 35 pm" src="https://user-images.githubusercontent.com/30636067/47396169-5700d400-d6ef-11e8-85d9-c69bac9df41f.png">

Here's the six records where those fields are left blank. 

I guess that also leads me to a follow up question for Matt: Do you know what the difference is for the records with IDs that are led with 10000________ and records that don't have that leading value? When I was going through trying to come up with the calculations for some of the fields in the processed data, I noticed that sometimes, facilities or accidents without that leading 10000________ are left out of the calculations. There's was no distinction between the two written out in the data documentation. 

If Matt doesn't know, might be worth asking the records custodians about that as well.
