### ISSUE TITLE
Move csv_dump into a django management command

### ISSUE THREAD

**Issue by gordonje** [rji-futures-lab/django-rmp-data#26]
This move the logic of this stand-alone script into a Django [management command](https://docs.djangoproject.com/en/2.1/howto/custom-management-commands/) in preparation for incorporating it into a full update routine for the data.

**Comment by thomasoide** [comment]
@gordonje I just did this, it was just a matter of joining the path of the database name. This command now works like this: 
1. Put desired .mdb file in the RMP Data Directory,
2. Run command to populate raw data folder. 

I'm having trouble with changing some of our ETL process locally right now, so this change to the management command will be reflected in my next PR.
