### ISSUE TITLE
Add CountyCd processed model

### ISSUE THREAD

**Issue by thomasoide** [rji-futures-lab/django-rmp-data#70]

**Comment by gordonje** [comment]
- [ ] Add `CountyCd` to `codes.py`
- [ ] Add `get_transform_queryset()` to the model (you can prob use `get_default_transform_queryset()`
- [ ] Add `CountyCd` to `rmp/models/processed/__init__.py`
- [ ] Add `CountyCd` to `rmp/models//__init__.py`
- [ ] Make `Facility.county_fips` a `CopyFromForeignKey`
- [ ] Make `Registration.county_fips` a `CopyFromForeignKey`
- [ ] Run `make syncdbschema` and `python manage.py updatermpdb`

You might have to use the `db_column` kwarg when defining the `CopyFromForeignKey` (as I did with the state fields).

BTW...I just noted that both `Facility` and  `Registration` have a `county` field on them already. We might need to delete those as well.

**Comment by thomasoide** [comment]
This is now complete on both Facility and Registration, should be able to add a search by county parameter now.
